export const Users = [
    {
      id:1,
      profilePicture: "persons/dp1.jpg",
      username: "Shaheer",
    },
    {
        id:2,
        profilePicture: "persons/dp2.jpg",
        username: "Shaheer Ahmed",
    },
    {
        id:3,
        profilePicture: "persons/dp3.jpg",
        username: "Obaid",
    },
    {
        id:4,
        profilePicture: "persons/dp4.jpg",
        username: "Reyyan",
    },
    {
      id:5,
      profilePicture: "persons/dp5.jpeg",
      username: "Mustafa",
    },
    {
      id:6,
      profilePicture: "person/6.jpeg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "person/7.jpeg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "person/8.jpeg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "person/9.jpeg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "person/10.jpeg",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Majestic Karakoram range!",
      photo: "post/mountains.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post/mycar.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Ronaldo supermacy!",
      photo: "post/ronaldo.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post/anime.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];